version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "DTrombett"
    commit-message:
      prefix: "deps"
      prefix-development: "devDeps"
      include: "scope"
    milestone: 3
    open-pull-requests-limit: 10
    reviewers:
      - "DTrombett"
