name: Run tasks on commit

on: 
  push:
    branches:
      - main

jobs:
  commit-tasks:
    name: Run tasks on commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install all dependencies
        run: npm ci

      - name: Deploy HTML pages
        run: npm run html

      - name: Run eslint
        run: npm run lint

      - name: Commit changes
        run: |
          git fetch
          git add .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "chore: deploy pages and lint source" || true
          git pull -r
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
