name: Run tasks on Pull Request

on: pull_request

jobs:
  pr-tasks:
    name: Run tasks on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge base branch
        run: |
          git fetch
          git checkout "${GITHUB_BASE_REF}"
          git checkout "${GITHUB_HEAD_REF}"
          git config user.name \"${GITHUB_ACTOR}\"
          git config user.email \"${GITHUB_ACTOR}@users.noreply.github.com\"
          git merge "${GITHUB_BASE_REF}"
          git push
